name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Remplacez "main" par le nom de la branche que vous souhaitez déployer

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build HTML
        run: |
          # Mettez ici les commandes nécessaires pour construire votre site HTML
          # Par exemple : npm run build ou hugo --minify

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist  # Remplacez "dist" par le dossier contenant votre site HTML
          BUILD_SCRIPT: npm run build  # Remplacez "npm run build" par la commande utilisée pour construire votre site HTML
